-- 
-- insert_device_exposure.sql
--
--  This is the insert for device_exposure generated by synpuf_etl.sql.  
--  Some values were hardcoded based on release notes and discussions with Claire & Erica. 
--

insert into cdm_synpuf_v667.dbo.device_exposure with (tablock) ( 
device_exposure_end_date, 
device_exposure_id, 
person_id, 
device_concept_id, 
device_exposure_start_date, 
device_type_concept_id, 
unique_device_id, 
quantity, 
provider_id, 
visit_occurrence_id, 
device_source_value, 
device_source_concept_id, 
device_exposure_start_datetime, 
device_exposure_end_datetime
)
select device_exposure_end_date, 
device_exposure_id, 
person_id, 
device_concept_id, 
device_exposure_start_date, 
device_type_concept_id, 
unique_device_id, 
quantity, 
provider_id, 
visit_occurrence_id, 
device_source_value, 
device_source_concept_id, 
cast('19000101' as datetime), -- device_exposure_start_datetime, 
NULL                          -- device_exposure_end_datetime 
from cdm_synpuf_v665.dbo.device_exposure;
