-- 
-- insert_observation.sql
--
--  This is the insert for observation generated by synpuf_etl.sql.  
--  Some values were hardcoded based on release notes and discussions with Claire & Erica. 
--

insert into cdm_synpuf_v667.dbo.observation with (tablock) ( 
observation_type_concept_id, 
value_as_number, 
value_as_string, 
value_as_concept_id, 
qualifier_concept_id, 
unit_concept_id, 
provider_id, 
visit_occurrence_id, 
observation_source_value, 
observation_source_concept_id, 
unit_source_value, 
qualifier_source_value, 
observation_id, 
person_id, 
observation_concept_id, 
observation_date, 
observation_datetime
)
select observation_type_concept_id, 
value_as_number, 
value_as_string, 
value_as_concept_id, 
qualifier_concept_id, 
unit_concept_id, 
provider_id, 
visit_occurrence_id, 
observation_source_value, 
observation_source_concept_id, 
unit_source_value, 
qualifier_source_value, 
observation_id, 
person_id, 
observation_concept_id, 
observation_date, 
NULL -- observation_datetime 
from cdm_synpuf_v665.dbo.observation;
