-- insert_cost.sql

-- Populate COST with DRUG_COST
insert into cdm_synpuf_v667.dbo.cost (
--cost_id, -- cost_id will be autogenerated
cost_event_id,
cost_domain_id,
cost_type_concept_id,
currency_concept_id,
total_charge,
total_cost,
total_paid,
paid_by_payer,
paid_by_patient,
paid_patient_copay,
paid_patient_coinsurance,
paid_patient_deductible,
paid_by_primary,
paid_ingredient_cost,
paid_dispensing_fee,
payer_plan_period_id,
amount_allowed,
revenue_code_concept_id,
reveue_code_source_value,
drg_concept_id,
drg_source_value,
)
select dc.drug_exposure_id,               -- cost_event_id
       'Drug',                       	  -- cost_domain_id
       0,                                 -- cost_type_concept_id
       dc.currency_concept_id,            -- currency_concept_id
       NULL,                              -- total_charge
       NULL,                              -- total_cost 
       dc.total_paid,                     -- total_paid 
       dc.paid_by_payer,                  -- paid_by_payer
       dc.total_out_of_pocket,            -- paid_by_patient
       dc.paid_copay,                     -- paid_patient_copay
       dc.paid_coinsurance,               -- paid_patient_coinsurance
       dc.paid_toward_deductible,         -- paid_patient_deductible
       dc.paid_by_coordination_benefits,  -- paid_by_primary
       dc.ingredient_cost,                -- paid_ingredient_cost
       dc.dispensing_fee,                 -- paid_dispensing_fee
       dc.payer_plan_period_id,           -- payer_plan_period_id
       NULL,                              -- amount_allowed 
       0,                                 -- revenue_code_concept_id
       NULL,                              -- reveue_code_source_value
       0,                                 -- drg_concept_id
       NULL                               -- drg_source_value
  from cdm_synpuf_v665.dbo.drug_cost     dc;


-- Populate COST with PROCEDURE_COST
insert into cdm_synpuf_v667.dbo.cost (
--cost_id, -- cost_id will be autogenerated
cost_event_id,
cost_domain_id,
cost_type_concept_id,
currency_concept_id,
total_charge,
total_cost,
total_paid,
paid_by_payer,
paid_by_patient,
paid_patient_copay,
paid_patient_coinsurance,
paid_patient_deductible,
paid_by_primary,
paid_ingredient_cost,
paid_dispensing_fee,
payer_plan_period_id,
amount_allowed,
revenue_code_concept_id,
reveue_code_source_value,
drg_concept_id,
drg_source_value,
)
select pc.procedure_occurrence_id,        -- cost_event_id
       'Procedure',                       -- cost_domain_id
       0,                                 -- cost_type_concept_id
       pc.currency_concept_id,            -- currency_concept_id
       NULL,                              -- total_charge
       NULL,                              -- total_cost 
       pc.total_paid,                     -- total_paid 
       pc.paid_by_payer,                  -- paid_by_payer
       pc.total_out_of_pocket,            -- paid_by_patient
       pc.paid_copay,                     -- paid_patient_copay
       pc.paid_coinsurance,               -- paid_patient_coinsurance
       pc.paid_toward_deductible,         -- paid_patient_deductible
       pc.paid_by_coordination_benefits,  -- paid_by_primary
       NULL,                              -- paid_ingredient_cost
       NULL,                              -- paid_dispensing_fee
       pc.payer_plan_period_id,           -- payer_plan_period_id
       NULL,                              -- amount_allowed 
       pc.revenue_code_concept_id,        -- revenue_code_concept_id
       pc.reveue_code_source_value,       -- reveue_code_source_value
       0,                                 -- drg_concept_id
       NULL                               -- drg_source_value
  from cdm_synpuf_v665.dbo.procedure_cost       pc;
