-- 
-- insert_observation_period.sql
--
--  This is the insert for observation_period generated by synpuf_etl.sql.  
--  Some values were hardcoded based on release notes and discussions with Claire & Erica. 
--

insert into cdm_synpuf_v667.dbo.observation_period with (tablock) ( 
period_type_concept_id, 
observation_period_end_date, 
observation_period_id, 
person_id, 
observation_period_start_date, 
observation_period_start_datetime, 
observation_period_end_datetime
)
select period_type_concept_id, 
observation_period_end_date, 
observation_period_id, 
person_id, 
observation_period_start_date, 
observation_period_start_date, -- observation_period_start_datetime, 
observation_period_end_date    -- observation_period_end_datetime
from cdm_synpuf_v665.dbo.observation_period;
