-- 
-- insert_person.sql
--
--  This is the insert for person generated by synpuf_etl.sql.  
--  Some values were hardcoded based on release notes and discussions with Claire & Erica. 
--


insert into cdm_synpuf_v667.dbo.person with (tablock) ( 
person_id, 
gender_concept_id, 
year_of_birth, 
month_of_birth, 
day_of_birth, 
race_concept_id, 
ethnicity_concept_id, 
location_id, 
provider_id, 
care_site_id, 
person_source_value, 
gender_source_value, 
gender_source_concept_id, 
race_source_value, 
race_source_concept_id, 
ethnicity_source_value, 
ethnicity_source_concept_id, 
birth_datetime
)
select person_id, 
gender_concept_id, 
year_of_birth, 
month_of_birth, 
day_of_birth, 
race_concept_id, 
ethnicity_concept_id, 
location_id, 
provider_id, 
care_site_id, 
person_source_value, 
gender_source_value, 
gender_source_concept_id, 
race_source_value, 
race_source_concept_id, 
ethnicity_source_value, 
ethnicity_source_concept_id, 
NULL -- birth_datetime
from cdm_synpuf_v665.dbo.person;
