-- 
-- insert_procedure_occurrence.sql
--
--  This is the insert for procedure_occurrence generated by synpuf_etl.sql.  
--  Some values were hardcoded based on release notes and discussions with Claire & Erica. 
--


insert into cdm_synpuf_v667.dbo.procedure_occurrence with (tablock) ( 
procedure_occurrence_id, 
person_id, 
procedure_concept_id, 
procedure_date, 
procedure_type_concept_id, 
modifier_concept_id, 
quantity, 
provider_id, 
visit_occurrence_id, 
procedure_source_value, 
procedure_source_concept_id, 
qualifier_source_value, 
procedure_datetime
)
select procedure_occurrence_id, 
person_id, 
procedure_concept_id, 
procedure_date, 
procedure_type_concept_id, 
modifier_concept_id, 
quantity, 
provider_id, 
visit_occurrence_id, 
procedure_source_value, 
procedure_source_concept_id, 
qualifier_source_value, 
procedure_date -- procedure_datetime 
from cdm_synpuf_v665.dbo.procedure_occurrence;
