-- 
-- insert_drug_exposure.sql
--
--  This is the insert for drug_exposure generated by synpuf_etl.sql.  
--  Some values were hardcoded based on release notes and discussions with Claire & Erica. 
--

insert into cdm_synpuf_v667.dbo.drug_exposure with (tablock) ( 
drug_exposure_id, 
person_id, 
drug_concept_id, 
drug_exposure_start_date, 
drug_exposure_end_date, 
drug_type_concept_id, 
stop_reason, 
refills, 
quantity, 
days_supply, 
sig, 
route_concept_id, 
lot_number, 
provider_id, 
visit_occurrence_id, 
drug_source_value, 
drug_source_concept_id, 
route_source_value, 
dose_unit_source_value, 
drug_exposure_end_datetime, 
verbatim_end_date, 
drug_exposure_start_datetime
)
select drug_exposure_id, 
person_id, 
drug_concept_id, 
coalesce(drug_exposure_start_date,cast('19000101' as datetime)), 
dateadd(dd,coalesce(days_supply,0),coalesce(drug_exposure_start_date,cast('19000101' as datetime))), 
drug_type_concept_id, 
stop_reason, 
refills, 
quantity, 
days_supply, 
sig, 
route_concept_id, 
lot_number, 
provider_id, 
visit_occurrence_id, 
drug_source_value, 
drug_source_concept_id, 
route_source_value, 
dose_unit_source_value, 
dateadd(dd,days_supply,coalesce(drug_exposure_start_date,cast('19000101' as datetime))), -- drug_exposure_end_datetime, 
NULL, -- verbatim_end_date, 
coalesce(drug_exposure_start_date,cast('19000101' as datetime))   -- drug_exposure_start_datetime
from cdm_synpuf_v665.dbo.drug_exposure;

