-- 
-- insert_measurement.sql
--
--  This is the insert for measurement generated by synpuf_etl.sql.  
--  Some values were hardcoded based on release notes and discussions with Claire & Erica. 
--

insert into cdm_synpuf_v667.dbo.measurement with (tablock) ( 
measurement_type_concept_id, 
operator_concept_id, 
value_as_number, 
value_as_concept_id, 
unit_concept_id, 
range_low, 
range_high, 
provider_id, 
visit_occurrence_id, 
measurement_source_value, 
measurement_source_concept_id, 
unit_source_value, 
value_source_value, 
measurement_id, 
person_id, 
measurement_concept_id, 
measurement_date, 
measurement_datetime
)
select measurement_type_concept_id, 
operator_concept_id, 
value_as_number, 
value_as_concept_id, 
unit_concept_id, 
range_low, 
range_high, 
provider_id, 
visit_occurrence_id, 
measurement_source_value, 
measurement_source_concept_id, 
unit_source_value, 
value_source_value, 
measurement_id, 
person_id, 
measurement_concept_id, 
measurement_date, 
NULL -- measurement_datetime 
from cdm_synpuf_v665.dbo.measurement;
